create: added get route for user profile details
willbryanta/ShelfSpace-server pull request #19
Opened 2024-10-31 22:32 UTC by willbryanta

I've deleted the user.js file - not sure why the changes come up still, but please review the GET route.

2024-10-31 22:34 UTC, Zarbba requested changes

2024-10-31 22:34 UTC, Zarbba commented on controllers/users.js
> +		const userProfile = await User.findById(req.params.userId)
I think this will need to be changed to 
`const userProfile = await User.findById(req.params.userId).populate('ownedReviews')`

2024-10-31 22:36 UTC, Zarbba commented on controllers/users.js
> +	try {
There's a missing gaurd phrase to protect the rotue:
`		if (!userProfile.isOwner(req.body.user)) {
			return res.status(403).json({
				error: "Oops! It doesn't look like that belongs to you!",
			})
		}
`

2024-11-01 01:47 UTC, willbryanta commented
Thanks Josh - I've updated in line with your comments. If we decide that we don't want to show the user's own reviews on their profile, I can always update this.

2024-11-01 02:37 UTC, Zarbba commented on controllers/users.js
>  			throw new Ettor("User not found")
```suggestion
			throw new Error("User not found")
```

2024-11-01 02:37 UTC, Zarbba commented on controllers/users.js
>  			throw new Ettor("User not found")
This method of throwing an error is slightly different to what we've applied elsewere but we can spend some time making things more consistent later. For now I'm happy to approve this. Just need to correct this typo.

2024-11-01 02:37 UTC, Zarbba approved these changes

2024-11-01 02:37 UTC, merged